[containers]
rome ansible_host=172.20.6.109
london ansible_host=172.20.6.108

[containers:vars]
ansible_user=cisco
ansible_password=cisco123
ansible_connection=ssh
# Bypass host key checking for lab environment ease of use
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
